"""add cost/income categories, document_date, paid_at

Revision ID: 18ae60e29410
Revises: 7beb7e9bc43a
Create Date: 2026-09-22 10:13:39.261825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ae60e29410'
down_revision: Union[str, None] = '7beb7e9bc43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('income_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('document_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key(
            'fk_expenses_category_id_cost_categories', 'cost_categories', ['category_id'], ['id'], ondelete='RESTRICT'
        )

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('document_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key(
            'fk_incomes_category_id_income_categories', 'income_categories', ['category_id'], ['id'], ondelete='RESTRICT'
        )

    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.Date(), nullable=True))

    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_column('document_date')

    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_column('paid_at')

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incomes_category_id_income_categories', type_='foreignkey')
        batch_op.drop_column('document_date')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_category_id_cost_categories', type_='foreignkey')
        batch_op.drop_column('document_date')
        batch_op.drop_column('category_id')

    op.drop_table('income_categories')
    op.drop_table('cost_categories')
    # ### end Alembic commands ###
