"""add participation comment/cost_category, salary default category setting

Revision ID: 57d0a18b1abb
Revises: 81996a875934
Create Date: 2026-09-29 13:47:43.486928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d0a18b1abb'
down_revision: Union[str, None] = '81996a875934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cost_category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_participations_cost_category',
            'cost_categories', ['cost_category_id'], ['id'], ondelete='SET NULL'
        )

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_salary_cost_category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_system_settings_salary_cost_category',
            'cost_categories', ['default_salary_cost_category_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_system_settings_salary_cost_category', type_='foreignkey')
        batch_op.drop_column('default_salary_cost_category_id')

    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_participations_cost_category', type_='foreignkey')
        batch_op.drop_column('cost_category_id')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
