"""add catalogs, settings, work service price, part purchase price

Revision ID: 7beb7e9bc43a
Revises: 7e993fd31b59
Create Date: 2026-09-08 16:55:07.516217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7beb7e9bc43a'
down_revision: Union[str, None] = '7e993fd31b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('default_purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['part_catalog_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['service_catalog_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.create_foreign_key(
            'fk_parts_catalog_item_id_part_catalog_items', 'part_catalog_items', ['catalog_item_id'], ['id'], ondelete='SET NULL'
        )

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('service_price', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.create_foreign_key(
            'fk_works_catalog_item_id_service_catalog_items', 'service_catalog_items', ['catalog_item_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_constraint('fk_works_catalog_item_id_service_catalog_items', type_='foreignkey')
        batch_op.drop_column('service_price')
        batch_op.drop_column('catalog_item_id')

    with op.batch_alter_table('parts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_parts_catalog_item_id_part_catalog_items', type_='foreignkey')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('catalog_item_id')

    op.drop_table('system_settings')
    op.drop_table('service_catalog_items')
    op.drop_table('part_catalog_items')
    # ### end Alembic commands ###
