"""add cash registers/documents, user.can_access_cash

Revision ID: 81996a875934
Revises: 18ae60e29410
Create Date: 2026-09-22 11:09:27.579239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81996a875934'
down_revision: Union[str, None] = '18ae60e29410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO cash_registers (id, name) VALUES (1, 'Касса')")
    op.create_table('cash_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('income', 'expense', name='cashdocumenttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_category_id', sa.Integer(), nullable=True),
    sa.Column('income_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cost_category_id'], ['cost_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['income_category_id'], ['income_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['register_id'], ['cash_registers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_access_cash', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_access_cash')

    op.drop_table('cash_documents')
    op.drop_table('cash_registers')
    # ### end Alembic commands ###
